[package]
name = "test-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
anyhow = "1.0.66"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
dyn-clone = "1.0.9"
indicatif = "0.17.2"
